language: python

notifications:
    email: false

python:
    - "2.7"


before_install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
      else
          wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda config --add channels pypi
    - conda info -a
    - deps='pip numpy scipy sphinx nose six future pep8'
    - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps 
    - source activate test-environment
    - pip install python-coveralls
    - pip install numpydoc
# add for profile
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq


install:
    - pip install -e .
    # add for profile
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - pip install nose-cprof
    - pip install properform


before_script:
    - pep8 mir_eval tests evaluators

script:
    - nosetests --with-coverage --cover-package=mir_eval --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_mir_eval_e6d1bc3b13_0
    - python -m properform Push 47.88.50.110:15554 asdf_mir_eval_e6d1bc3b13_0 ./tests/profile_mir_eval_e6d1bc3b13_0
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar

after_success:
    - coveralls
 #2017-08-27 23:02:03 modified at 0